export const TOGGLE_SIGNUP_DRAWER = "TOGGLE_SIGNUP_DRAWER";
export const TOGGLE_LOGIN_DRAWER = "TOGGLE_LOGIN_DRAWER";
export const REGISTER_INQUIRY = "REGISTER_INQUIRY";
export const REQUEST = "REQUEST";
export const FAILED_INQUIRY_REQUEST = "FAILED_INQUIRY_REQUEST";
export const CLEARING_PROPS = "CLEARING_PROPS"
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const TOGGLE_CONTACT_US_DRAWER = "TOGGLE_CONTACT_US_DRAWER";
